# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c82da416bf7b3d0552cd9d9349be9da90763c495b81fed2d712fb066e3646f84248f18e1936d73e27cb84aa9478b3a1b32235af6320e8057fec87015f26d4a3d

test:
  secret_key_base: 3a2b8c75b7a2ff4f71bda1a2fe83d34ee8f09e9a33831b6c1430cc4df187bdfc8ce00013d8b25dffc71a1563fe3e708557b5ea859c09810ff50fa93d90a959d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
